### ISSUE TITLE
Setting one NumberElement sometimes sets many

### ISSUE THREAD

**Issue by kvangorkom** [magao-x/purepyindi#4]
I haven't been able to consistently reproduce this, but sometimes setting one NumberElement sets other NumberElements associated with that Property. I've only seen this behavior in the dmModes INDI devices, so I'm not sure how general it is. Setting these elements in cursesINDI behaves as expected.

 In the example below, the command
`client['ncpcModes.target_amps.02'] = 0.1`
sets all elements after '02' to 0.1, while
`client['ncpcModes.current_amps.02'] = 0.1`
only sets '02' (as expected).

Code that will _sometimes_ reproduce this behavior:
```
In [1]: from purepyindi import INDIClient
In [2]: client = INDIClient('localhost', 7624)
In [3]: client.start()
In [4]: elems = client.devices['ncpcModes'].properties['current_amps'].elements
In [5]: for e in elems.values():
    ...:     print(e.value)
    ...:
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
In [6]: client['ncpcModes.target_amps.02'] = 0.1
In [7]: for e in elems.values():
    ...:     print(e.value)
    ...:
0.0
0.0
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
0.1
In [8]: client['ncpcModes.target_amps.02'] = 0.0 # reset all to 0
In [9]: client['ncpcModes.current_amps.02'] = 0.1 # but this works
In [10]: for e in elems.values():
    ...:     print(e.value)
    ...:
    ...:
0.0
0.0
0.1
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
```

**Comment by joseph-long** [comment]
This is my fault for being spec compliant. I’ll stop.

**Comment by jaredmales** [comment]
is this just an issue with dm modes?

**Comment by joseph-long** [comment]
I’m pretty sure I know why this happens. The purepyindi client sends all elements of a numbervector according to the spec, but I think Libcommon does not. Then there’s not atomic assignment of multiple elements with the api as currently done, so things get race condition-y.

**Comment by joseph-long** [comment]
Now that I've had time to read the report more closely (and check what dmMode.hpp does), I'm less confident I know why this is happening. We need to enable verbose logging and see what gets sent...

**Comment by joseph-long** [comment]
Fixed in https://github.com/magao-x/purepyindi/commit/8c0dbb2abbf22e0c60af2c2510cdbb078aa2c442. Looks like libcommon / lilxml doesn't handle self-closing XML tags for the elements that are `None` (and hence should have no body), so it was reusing the body text value for the one we were trying to set as the body text value for all subsequent elements.
